ND Array \
ndarray plus rapide, meilleur aux calculs scientifiques

ndarray.shape \
quels est la lignes , la forme, combient colonne, profondeur \
shape est un tuple \
shape = (2,3) \
shape[0] = 2 -> nb de ligne \
shape[1] = 3 -> nb de colonne \
shape -> immutable 

In [9]:
import numpy as np

In [3]:
 A = np.array([1, 2, 3])
A

array([1, 2, 3])

In [4]:
A.shape

(3,)

In [5]:
A.ndim

1

In [6]:
A.size

3

Initialiser avec des 0

In [8]:
B = np.zeros((3,2))
B

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [9]:
B.shape

(3, 2)

In [10]:
B.size

6

Initialiser avec des 1

In [20]:
C = np.ones((4,7))
C

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [22]:
C.size

28

In [24]:
D = np.full((2,3),7)
D

array([[7, 7, 7],
       [7, 7, 7]])

In [26]:
np.random.seed(312098)
np.random.randn(3,4)

array([[ 1.2824656 ,  0.70519288, -1.71966591, -0.96709965],
       [-0.03140678, -0.59476713,  0.59382329,  1.44692847],
       [ 0.00404294, -0.05312601, -0.96163844,  0.00219315]])

## Matrice identiter
np.eye(4)

In [29]:
# début, fin , quantité d'élement qu'on va avoir dans notre tableau 
# répatie de façon égale entre notre point de début et notre point de fin 
np.linspace(0, 10, 20, dtype=np.float16)

array([ 0.    ,  0.5264,  1.053 ,  1.579 ,  2.105 ,  2.63  ,  3.158 ,
        3.684 ,  4.21  ,  4.74  ,  5.26  ,  5.79  ,  6.316 ,  6.844 ,
        7.367 ,  7.895 ,  8.42  ,  8.945 ,  9.48  , 10.    ],
      dtype=float16)

In [31]:
# début, fin, pas 
np.arange(0,10,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [47]:
# dtype = data type  


# Manipulation 

In [33]:
K = np.zeros((3,2))
L = np.ones((3,2))

In [37]:
K

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [39]:
L

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [35]:
# Colonne coller au une au autre 
M = np.hstack((K,L))
M

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [62]:
# Ligne coller au une après les autre
N = np.vstack((K,L))
N

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [41]:
# 1 -> colonne
np.concatenate((K, L), axis= 1)

array([[0., 0., 1., 1.],
       [0., 0., 1., 1.],
       [0., 0., 1., 1.]])

In [43]:
# 0 -> ligne
X = np.concatenate((K, L), axis= 0)
X

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [45]:
# reshape : remanipuler la forme du tableau pour lui donner un nouvel forme à condition qu'il nb initiale = nb finale 
Z = X.reshape((3,4))
Z

array([[0., 0., 0., 0.],
       [0., 0., 1., 1.],
       [1., 1., 1., 1.]])

In [53]:
F = X.reshape((2,6))
F

array([[0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1.]])

In [47]:
P = np.array([1,2,3])
P= P.reshape((P.shape[0],1))
P.shape

(3, 1)

In [49]:
P = P.squeeze()
P.shape

(3,)

In [51]:
# Aplatir un tableau en une seul dimension
Z.ravel()

array([0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1.])

In [153]:
def initialisation(m,n):
    # m: nombre de lignes
    # n: nombre de colonnes
    # retourne une matrice aléatoire (m, n+1)
    # avec une colonne biais (replie de '1') tout a droite
    # reshape 
    # random.randn 
    # concatenate
    D = np.ones((m, 1))
    F = np.random.randn(m,n)
    K = np.concatenate((F,D), axis =1 )
    return K

In [155]:
initialisation(3,4)

array([[ 1.08417424, -0.37123147, -0.6251293 , -0.35830499,  1.        ],
       [ 2.27834768,  1.00738681,  0.12183351,  0.49315804,  1.        ],
       [-1.34090349, -0.93557502,  0.03147052,  1.57908985,  1.        ]])

In [151]:
def initialization(m,n):
    X = np.random.randn(m,n)
    X = np.concatenate((X, np.ones((X.shape[0],1))), axis = 1)
    return X
initialization(3,4)

array([[ 0.76271137,  0.35018956,  0.90187736, -2.21279988,  1.        ],
       [ 0.86891347, -1.25065263, -1.25712371, -0.49191062,  1.        ],
       [-0.28027523, -1.30278044,  0.44614585, -0.36662028,  1.        ]])