In [1]:
import numpy as np 

In [5]:
np.random.seed(0)
A= np.random.randint(0,10,[2,3])
A

array([[5, 0, 3],
       [3, 7, 9]])

# Méthodes ndarray

In [8]:
A.sum()

27

In [10]:
A.sum(axis=0)

array([ 8,  7, 12])

In [12]:
A.sum(axis=1)

array([ 8, 19])

In [14]:
# Somme cumuler
A.cumsum()

array([ 5,  5,  8, 11, 18, 27])

In [16]:
A.cumprod()

array([5, 0, 0, 0, 0, 0])

In [18]:
A.min(axis=0)

array([3, 0, 3])

In [22]:
# Trouver la position du min
A.argmin(axis=0)

array([1, 0, 0], dtype=int64)

In [24]:
# A.argsort() retourne les index dans l'ordre de tri du tableau A, sans modifier le tableau A (il n'est pas trié)
A.argsort()

array([[1, 2, 0],
       [0, 1, 2]], dtype=int64)

In [26]:
np.exp(A)

array([[1.48413159e+02, 1.00000000e+00, 2.00855369e+01],
       [2.00855369e+01, 1.09663316e+03, 8.10308393e+03]])

In [30]:
np.log(A)

C:\Users\hp\AppData\Local\Temp\ipykernel_41620\2475394391.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(A)


array([[1.60943791,       -inf, 1.09861229],
       [1.09861229, 1.94591015, 2.19722458]])

# Statistiques

In [34]:
A 

array([[5, 0, 3],
       [3, 7, 9]])

In [40]:
A.mean(axis=0)

array([4. , 3.5, 6. ])

In [42]:
# Ecart type
A.std()

2.9297326385411577

In [44]:
# Variance
A.var()

8.583333333333334

In [52]:
# coefficient de correlation 
# indique la correlation qui existe entre les différentes lignes
np.corrcoef(A)[0,1]

-0.5636214801906779

In [62]:
np.random.seed(0)
B = np.random.randint(0,10,[5,5])
B

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [64]:
# Compter le nombre de fois qu'un valeur répète dans un tableau numpy
values, counts = np.unique(B,return_counts=True)

In [70]:
values[counts.argsort()]

array([0, 2, 1, 4, 6, 3, 5, 9, 7, 8])

In [72]:
for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'valeur {i} apparait {j}')

valeur 0 apparait 1
valeur 2 apparait 1
valeur 1 apparait 2
valeur 4 apparait 2
valeur 6 apparait 2
valeur 3 apparait 3
valeur 5 apparait 3
valeur 9 apparait 3
valeur 7 apparait 4
valeur 8 apparait 4


# NAN Corrections

In [87]:
# Not a Number
C = np.random.randn(5,5)
C[0,2] = np.nan
C[4,3] = np.nan
C

array([[-1.45436567,  0.04575852,         nan,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218],
       [-0.4380743 , -1.25279536,  0.77749036,         nan, -0.21274028]])

In [81]:
np.nanmean(C)

4.5

In [83]:
np.nanstd(C)

2.9297326385411577

In [95]:
np.isnan(C).sum()/C.size

0.08

In [103]:
C[np.isnan(C)]  = 0
C

array([[-1.45436567,  0.04575852,  0.        ,  1.53277921,  1.46935877],
       [ 0.15494743,  0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 , -0.50965218],
       [-0.4380743 , -1.25279536,  0.77749036,  0.        , -0.21274028]])

# Algebre Linéaire

In [106]:
D = np.ones((2,3))
E = np.ones((3,2))
D

array([[1., 1., 1.],
       [1., 1., 1.]])

In [108]:
E

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [110]:
# Transposer une matrice
D.T

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [112]:
# Produit matricielle
# (2,3)*(3,2)=(2,2)
D.dot(E)

array([[3., 3.],
       [3., 3.]])

In [114]:
# (3,2)*(2,3)=(3,3)
E.dot(D)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [116]:
F = np.random.randint(0,10,[3,3])
F

array([[7, 5, 5],
       [0, 1, 5],
       [9, 3, 0]])

In [120]:
# Calculer le determinant 
np.linalg.det(F)

75.00000000000004

In [122]:
# Inverser la matrice 
np.linalg.inv(F)

array([[-0.2       ,  0.2       ,  0.26666667],
       [ 0.6       , -0.6       , -0.46666667],
       [-0.12      ,  0.32      ,  0.09333333]])

In [124]:
# pseudo inverse : si il y a une combinaison linéaire entre les lignes et les colonnes 
np.linalg.pinv(F)

array([[-0.2       ,  0.2       ,  0.26666667],
       [ 0.6       , -0.6       , -0.46666667],
       [-0.12      ,  0.32      ,  0.09333333]])

In [134]:
# Valeur propre d'une matrice (eigen value)
# Réduction de dimession (Principal component analysis)
# Vecteur propre d'une matrice (eigen vectors)
np.linalg.eig(F)

EigResult(eigenvalues=array([12.65598352+0.j        , -2.32799176+0.71169169j,
       -2.32799176-0.71169169j]), eigenvectors=array([[-0.75766826+0.j        , -0.1407341 -0.0730122j ,
        -0.1407341 +0.0730122j ],
       [-0.25728647+0.j        ,  0.81622126+0.j        ,
         0.81622126-0.j        ],
       [-0.59978537+0.j        , -0.54327552+0.11617958j,
        -0.54327552-0.11617958j]]))

# Exercice
Standardiser la matrice A sur chaque colonne \
Résultat: chaque colonne doit avoir moyenne = 0 et écart type = 1

In [162]:
np.random.seed(0)
G = np.random.randint(0,100,[10,5])
G

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [164]:
# Standardiser : mettre sur une même échelle chaque ligne et colonne de notre dataset
# Mise à l'echelle: (x-min(x))/(max(x)-min(x))
# Normalisation avec la moyenne: (x-average(x))/(max(x)-min(x))
# Z-score Normalization : (x-mean(x))/std(x)

In [166]:
G.mean(axis=0)

array([44.5, 47. , 60.5, 45.7, 64.5])

In [168]:
G.std(axis=0)

array([22.66384786, 22.28003591, 26.5678377 , 29.36341261, 23.2432786 ])

In [170]:
G = (G-G.mean(axis=0))/G.std(axis=0)
G

array([[-0.02206157,  0.        ,  0.13173823,  0.72539252,  0.10755798],
       [-1.56637126,  1.61579632, -1.48676006, -0.33034307,  0.96802178],
       [ 1.12513992,  1.84021247,  1.03508612, -1.14768676, -0.27965074],
       [ 0.90452425, -0.35906585,  0.99744662,  0.0102168 ,  1.01104497],
       [ 1.6104944 , -0.44883231, -1.33620208,  1.0659524 ,  0.32267393],
       [-1.56637126, -1.21184724,  0.73397016,  0.7935045 ,  0.62383626],
       [ 0.11030784,  0.76301493,  0.80924915,  1.81518411,  1.01104497],
       [ 0.1985541 , -0.80789816, -1.56203905, -0.90929485, -2.17267111],
       [-0.24267724, -0.67324847,  0.16937773, -1.24985473, -0.32267393],
       [-0.55153918, -0.7181317 ,  0.50813319, -0.77307091, -1.26918412]])

In [172]:
G.mean(axis=0)

array([-2.22044605e-17, -4.44089210e-17,  0.00000000e+00, -1.22124533e-16,
       -4.44089210e-17])

In [176]:
G.std(axis=0)

array([1., 1., 1., 1., 1.])

In [178]:
G.shape

(10, 5)

In [180]:
G.size

50