In [1]:
import numpy as np

In [16]:
np.random.seed(0)
A = np.random.randint(0,10, [2,3])
A

array([[5, 0, 3],
       [3, 7, 9]])

# Méthodes ndarray

In [18]:
A.sum()

27

In [22]:
A.sum(axis=0) 
# vertical |

array([ 8,  7, 12])

In [24]:
A.sum(axis=1)
# horizontal ----

array([ 8, 19])

In [42]:
A.cumsum(axis=1)

array([[ 5,  5,  8],
       [ 3, 10, 19]])

In [44]:
A.prod(axis=0)

array([15,  0, 27])

In [46]:
A.min(axis=0)

array([3, 0, 3])

In [54]:
A.argmax(axis=1)
# Retourne la position du max (arg)

array([0, 2], dtype=int64)

In [71]:
# trie le tableau A
A.sort()
A

array([[0, 3, 5],
       [3, 7, 9]])