#  Broadcasting \ 
* A et B dimensions égales ou égales à 1
* Même nb de ligne en A, même nb de ligne en B
* Même nb de colonne en A , même nb de colonne en B
* Lorsqu'il y a une différence dans A et B , donc la dimension respective est = 1  


In [2]:
import numpy as np 

In [8]:
np.random.seed(0)
A = np.random.randint(0,10,[2,3])
B = np.ones((2,3))

In [11]:
A

array([[5, 0, 3],
       [3, 7, 9]])

In [13]:
B

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
A+B

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

In [17]:
# Le broadcasting consiste à étendre les dimesions d'un tableau 
A + 2

array([[ 7,  2,  5],
       [ 5,  9, 11]])

In [19]:
# vecteur : comprend 2 éléments 
C = np.ones((2,1))
A+C

array([[ 6.,  1.,  4.],
       [ 4.,  8., 10.]])

In [23]:
np.random.seed(0)
M = np.random.randint(0,10,[4,1])
N = np.ones((1,3))

In [25]:
M

array([[5],
       [0],
       [3],
       [3]])

In [27]:
N

array([[1., 1., 1.]])

In [29]:
M+N

array([[6., 6., 6.],
       [1., 1., 1.],
       [4., 4., 4.],
       [4., 4., 4.]])

In [49]:
np.random.seed(0)
M = np.random.randint(0,10,[4,1])
N = np.ones((5,))
N

array([1., 1., 1., 1., 1.])

In [51]:
M

array([[5],
       [0],
       [3],
       [3]])

In [53]:
M+N

array([[6., 6., 6., 6., 6.],
       [1., 1., 1., 1., 1.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])