Numpy

In [9]:
import numpy as np
nom = ['Rasoa','Rabe', 'Rakoto', 'Rahery']
# liste indexe; dictionnaire k:v
nom[1]
tab= np.array ([1,2,3,4])
tab

array([1, 2, 3, 4])

In [11]:
# list dans une list aza adino ny [[]]
tab2= np.array([[1,2,3],[4,5,6],[7,8,9]])
tab2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
zero=np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
tab3 = np.ones((3,3))
tab3

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [17]:
tab4 = np.arange(0,10,2)
tab4

array([0, 2, 4, 6, 8])

In [19]:
# nombre générer de manière imprévisible; pseudo-aléatoire 
# distribution unifforme [0,1] np.random.rand
ran_tab = np.random.rand(3,3)*100
ran_tab

array([[20.92110365, 36.10410197, 85.00522313],
       [52.50987304, 45.92744461, 28.45327808],
       [79.71878101, 10.06681179, 38.89016063]])

In [21]:
# distribution discret générer nombre aléatoire dans une intervalle spécifique np.random.randint() ->entire
tab5= np.random.randint(10,50)
tab5

34

In [23]:
# distribution normal ou gausienne manaraka loi normale -> ML
tab6 = np.random.randn(1,5)
tab6

array([[ 1.04144442, -1.3090977 ,  1.61339176,  1.36876266,  1.28563386]])

In [25]:
# Fixer le nombre aléatoire .scid parametre=seed 42 ou seed 101
np.random.seed(42)
tab7 = np.random.rand(5,10)
print(tab7)

[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
  0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497 0.18340451
  0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998 0.78517596
  0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
  0.30461377 0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204  0.25877998 0.66252228
  0.31171108 0.52006802 0.54671028 0.18485446]]


In [27]:
# regression linéaire simple y=ax+b+e -> prédiction estimation
# randoom forest y=1/1+e-x
# regression logistique
# algo superviser 
# distribution discret


Indexation et selection 

In [30]:
table = np.array([10,20,30,40,50])
table[2] 

30

In [32]:
table1= np.array([[1,2,3], [4,5,6],[7,8,9]])
table1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
table1[0,0]

1

In [36]:
# 2: hatrany @faranay
table1[0,1:]

array([2, 3])

In [46]:
table1[1,1:]

array([5, 6])

In [48]:
table1[2,1:]

array([8, 9])

In [52]:
table1[2,:-1]

array([7, 8])

In [54]:
table1[:2,1]

array([2, 5])

In [ ]:
table[:-2,]